insert into usuario (direccion, password, username, email) values ('Room 1840', '$2a$04$MhBkP6JEnGqzjkYF//uhEe5.VHGpUbduZSGX3qiuN0raANKc1f7sG', 'hbellhanger0', 'gtaree0@indiegogo.com');
insert into usuario (direccion, password, username, email) values ('Suite 69', '$2a$04$W7Kq/KRSLFHosySt9/85mOpQUzqiAwPqtgW2JaFpd6XB4k/8l3vaS', 'mfairfull1', 'jbitten1@cmu.edu');
insert into usuario (direccion, password, username, email) values ('Room 1673', '$2a$04$WRxQgGTrmOWIesiw9iNneukoIk5bik5V5xXTVSRNmQeGMm2CyGg3G', 'cvidineev2', 'ereyson2@netscape.com');
insert into usuario (direccion, password, username, email) values ('Suite 31', '$2a$04$g689f4oYSv2PKpAKPZ0Yt.XocpJqkmrtWGdF7j0yNEG2nsouzgBsS', 'abarenskie3', 'scecere3@newsvine.com');
insert into usuario (direccion, password, username, email) values ('Suite 48', '$2a$04$Pv/zx.gXF0l1sBjrqKwwsuDPVp5lEFckbPOxCTWeuooYEmixntO32', 'athebe4', 'hguerre4@nbcnews.com');
insert into usuario (direccion, password, username, email) values ('Room 1282', '$2a$04$jHM7T0fckS07oswiaCemfeU3n96C58eeMmiFDWDQQ3rARRU0V7SXO', 'abaptist5', 'rartinstall5@webeden.co.uk');
insert into usuario (direccion, password, username, email) values ('PO Box 23283', '$2a$04$nj87C4QR2R9GyuEDA3k5h.Ehw4YXXuJOeeGgceFJrhINXJuWrZrFK', 'cdiprose6', 'cgianolini6@icq.com');
insert into usuario (direccion, password, username, email) values ('6th Floor', '$2a$04$mUVjk.NrjiK3egT3fTVebOj7o7mMv46TyhhfbVqK1IfvcG9VjoCaq', 'cglendining7', 'adyhouse7@barnesandnoble.com');
insert into usuario (direccion, password, username, email) values ('PO Box 40723', '$2a$04$5vtaDC1AB8IZ//Hlrz1fVOEQ.bEgLe8ULQeM6UVRC07akRj0PN0/a', 'memons8', 'ejurgen8@about.me');
insert into usuario (direccion, password, username, email) values ('PO Box 3659', '$2a$04$VjnaXWE2/.MgsBdkDpauR.swSVgKozOk78RNmI3ggA7bkPJruJi3m', 'brome9', 'tmacneilly9@free.fr');
insert into usuario (direccion, password, username, email) values ('Suite 34', '$2a$04$70OrhL0A7Kv6rIlZo0E8jO.eivt.TzNW6uFLD8.BxpS5Jrdi96myK', 'jbeardsa', 'kbriggdalea@cnet.com');
insert into usuario (direccion, password, username, email) values ('PO Box 30295', '$2a$04$Q/1xQesysuEmQJR/N2p.M.axzEYslerrL2moZOL4W24sBAlguZZpq', 'dwadhamb', 'nblindermannb@1688.com');
insert into usuario (direccion, password, username, email) values ('7th Floor', '$2a$04$sFRQen51rrqx6axG5IUfZOmXcl2KajcN0MOjb9vLaf0H8n40WtWDu', 'dbatchanc', 'pyoutheadc@japanpost.jp');
insert into usuario (direccion, password, username, email) values ('Apt 1617', '$2a$04$Sc3Fuhwg2F565n4oFg7Dgu8bgFGiXZqmIr.8bDgsmHxSxEDcEZCQ2', 'pedied', 'liannuzzid@jigsy.com');
insert into usuario (direccion, password, username, email) values ('Apt 1224', '$2a$04$4tBcLExteJPIfZlJb0IHb.8uelL3G1T0AoAbLDQl.vLbP4.XV.RMu', 'ecrumpe', 'daltoftse@chicagotribune.com');
insert into usuario (direccion, password, username, email) values ('PO Box 63740', '$2a$04$pl7HHy1cvfdAXd0dK2rw3uT5uzC1UxsrRgahvzN83C.sHAEml1Ab6', 'bharef', 'rhargerief@exblog.jp');
insert into usuario (direccion, password, username, email) values ('Suite 92', '$2a$04$pIbC.C7Rr.rynmDbegeHpuk.0EkCK0PlbaHxM4brVXTszykWvP/LW', 'shubnerg', 'lquickendeng@github.com');
insert into usuario (direccion, password, username, email) values ('Suite 32', '$2a$04$WJeIu0q6Mn16fWNuwjB1meFKrj/gOIa0skrgBeOZcfqGhbxlraKgC', 'tmaccartairh', 'vrobbieh@cisco.com');
insert into usuario (direccion, password, username, email) values ('Suite 92', '$2a$04$ZkFLBt3LvJL.MXEKSTPoTuDgOFKoDHj.Dc/FzSE79SB3UkL5DtS9.', 'oshallikeri', 'mkettlestringi@umn.edu');
insert into usuario (direccion, password, username, email) values ('PO Box 49668', '$2a$04$4OD7PeFX6eg4m/ck8CD.a.1i1yYUKjG5OjKwaPY6nWX.PfckRZNty', 'rbourj', 'kjohnseyj@army.mil');
insert into usuario (direccion, password, username, email) values ('15th Floor', '$2a$04$hDnMuCPKo3g8Zxn31vD4..YiKRpjkGRHyYMngmqchxjv5FvWe9Lua', 'tpetruskevichk', 'hleekek@timesonline.co.uk');
insert into usuario (direccion, password, username, email) values ('Suite 81', '$2a$04$4KChKICKYYSkTWt9ESHDi.0upyYXAYniLTtYVSokjFzhGZ2ABsOsi', 'kgleadhelll', 'scaretl@nytimes.com');
insert into usuario (direccion, password, username, email) values ('13th Floor', '$2a$04$DZgW4aWGf6HsAgCxYpW5Ke6laYWDmQM6zzfJvSEF/hTeBpNZ9KbTW', 'cmenpesm', 'sedgingtonm@zimbio.com');
insert into usuario (direccion, password, username, email) values ('Suite 51', '$2a$04$yEUE/oDNnF.svu.unowiYuq85AaHcSEu9rG5fkssowMOFCCzds8vm', 'bgannicleffn', 'sdowdneyn@4shared.com');
insert into usuario (direccion, password, username, email) values ('Room 1427', '$2a$04$i/yrIsOjk3KYU0m28HPlpux6K.7JxV3RYzRHr1kYZtQ4aBQGx.uuC', 'hhawksleeo', 'jmeiklejohno@hp.com');
insert into usuario (direccion, password, username, email) values ('PO Box 79133', '$2a$04$mer/Ei/DIslm6Z61ROiLTe63ktJZR2A3bJiu4fLVf19H7V1JncXSK', 'bgellertp', 'abashfordp@creativecommons.org');
insert into usuario (direccion, password, username, email) values ('PO Box 51832', '$2a$04$P2IJ8uHSnTBbY7iDyhk2JOeKUUhIgW20Lv0Jruwo6u/DoK2wxsobi', 'scoskerryq', 'byakubowiczq@stumbleupon.com');
insert into usuario (direccion, password, username, email) values ('Room 1660', '$2a$04$0agJf2URPCfODgGqXQZPeOP3.nz1U/Gr7hO7i26YoDoTlSwfBGabK', 'mpurseglover', 'xsarlr@google.co.uk');
insert into usuario (direccion, password, username, email) values ('Room 1270', '$2a$04$uIYdfnbikovtfrbrgYAykOilFVQtnxKdPq3A29iakHo4/qAU/cGjq', 'ctschersichs', 'lwinsleys@jalbum.net');
insert into usuario (direccion, password, username, email) values ('Room 1706', '$2a$04$MIauUZBY4TKDTyF1Nl193eaYuyDQeNRdfj284Es1EWzo6Xhu7.1s6', 'jcollerdt', 'ebridgwoodt@samsung.com');
insert into usuario (direccion, password, username, email) values ('Suite 4', '$2a$04$T.yYgWvJoKOYCPMJjTsfmOEbev479c2rZAOd7qC/vTlZmMjTcHFZW', 'drapeu', 'bveelersu@storify.com');
insert into usuario (direccion, password, username, email) values ('Apt 559', '$2a$04$SHn1iOzdYgA0touaEFYFPuGkiKOEfRpZy0KA5TW.b90INzZcQqfGm', 'fflethamv', 'bcroyv@fc2.com');
insert into usuario (direccion, password, username, email) values ('Suite 60', '$2a$04$mCvjIHjkrbav9/.SwuRHauKEqTkjClN6tJue229cdEPBo/Mgpq5CC', 'astrugnellw', 'hsobtkaw@lycos.com');
insert into usuario (direccion, password, username, email) values ('11th Floor', '$2a$04$DFcUy4CEcrl8EXp3KcW3gOZA4JGbE.TivL5ORHWhVGN/xPvCBiIXu', 'onecoldsx', 'lshordx@cbsnews.com');
insert into usuario (direccion, password, username, email) values ('Suite 71', '$2a$04$2n2sw6IBTFkH4CIW0utM7u8PP1bXo/blZmGsXY26dqmfTdzzAbPai', 'alovelly', 'jfredericky@theglobeandmail.com');
insert into usuario (direccion, password, username, email) values ('PO Box 58448', '$2a$04$wl6OkkZWHjwIF5Ibue/h4e70NE3fy89AoN6vLFacg03G0P0Qzp6vy', 'ayuillz', 'qolerenshawz@yahoo.com');
insert into usuario (direccion, password, username, email) values ('8th Floor', '$2a$04$99CwpeU52YHqCxqnq4xqPe29KT7PTrXj72gqwNpo3B0ljVVS5kN5i', 'iswinbourne10', 'asteers10@wiley.com');
insert into usuario (direccion, password, username, email) values ('PO Box 60286', '$2a$04$NW0B40XFauSkk./eEyRD/emvhoFkpuF17dxiYhLGPAkWJ/Z8C2Eki', 'lsaura11', 'nelcott11@prnewswire.com');
insert into usuario (direccion, password, username, email) values ('Apt 1999', '$2a$04$ETlsYVwqif8D9.TfYaBx/.D5BUDOTrB1hPnMfE5L4vQD9r1r1eVfu', 'mhatto12', 'bbaiss12@issuu.com');
insert into usuario (direccion, password, username, email) values ('Apt 1854', '$2a$04$Ztfpt5Ma2p3JISvtBMREhOOo2fjKnoEHu85t5FqBL/BV.3t99kz1e', 'wokeenan13', 'dbatson13@imageshack.us');
insert into usuario (direccion, password, username, email) values ('Room 1589', '$2a$04$2.0JZpOWJ1aFi15DR3SlSuxZcH.ROHnsSH8wDWVYkpHcFrB2dXi0G', 'bglitherow14', 'ogreen14@state.gov');
insert into usuario (direccion, password, username, email) values ('Apt 1239', '$2a$04$W8oI5Qn0WFUxn0.zZWXZYO/UQ7Rs5QmaTn/SZPB7Lu1qAGPcSGbYi', 'fwhillock15', 'jclaricoates15@samsung.com');
insert into usuario (direccion, password, username, email) values ('Apt 1411', '$2a$04$uLN5iLRtIXxaaENR3I35TOb9N34SzZALJSlI5MRbrPYUkDGpkXMVW', 'wbeeble16', 'hhylden16@mlb.com');
insert into usuario (direccion, password, username, email) values ('11th Floor', '$2a$04$88z0O/VqEPwiGYm4x3bxsOHuvsl9dYSG4VkKSIdsBYRk.isD0/gUW', 'ndelf17', 'askerman17@imgur.com');
insert into usuario (direccion, password, username, email) values ('Apt 439', '$2a$04$Q4Yxj39Hy1W.nZ8pEQ5kpuxhqO74tMsbKXManjAQw5QJxXrd5SrlO', 'aperacco18', 'nwillishire18@google.fr');
insert into usuario (direccion, password, username, email) values ('PO Box 10464', '$2a$04$KldjwNAqaEcik8VPZOz6QOudfi58pyjvqm88XaWFhxrv2GCtO/Xmi', 'sbinham19', 'sformie19@typepad.com');
insert into usuario (direccion, password, username, email) values ('PO Box 72691', '$2a$04$MQIp1KNBmvXTsyP97fBuxec170T/PdU/eHriQ9LRAqGwjYKkpIB.W', 'bdisley1a', 'mtreen1a@washington.edu');
insert into usuario (direccion, password, username, email) values ('Apt 1198', '$2a$04$PiCC6NcDmy4gaMPRxJknauUQ2KkdLzSLlPVMwSuTny7oao32jRKl.', 'lcapelin1b', 'hfancott1b@ihg.com');
insert into usuario (direccion, password, username, email) values ('12th Floor', '$2a$04$Aic/cMgxHUIbAlZskANmU.m1IIGKnCyJ2.nJIRLuJoObL4j.Eo0yW', 'pambroise1c', 'dheineke1c@google.nl');
insert into usuario (direccion, password, username, email) values ('Apt 812', '$2a$04$ljgcdaDmqLo64P6Iugvpu.ELSFqcmXjqVKXxlMxRkk3RngeSniyCW', 'zbudik1d', 'aswayton1d@phoca.cz');
insert into usuario (direccion, password, username, email) values ('Apt 1353', '$2a$04$3M4orrfRWCX75t/ib4NZfOzulYqopLnn8Mk.UsnlYppM023Ye7.iu', 'cpresser1e', 'mflecknoe1e@ifeng.com');
insert into usuario (direccion, password, username, email) values ('Room 533', '$2a$04$XjZx0HDv/dTfVqFgLyx2ReHyWPVrhYiz9sbyj.wFR6l.9Pl1ahK6y', 'sezele1f', 'praulstone1f@comsenz.com');
insert into usuario (direccion, password, username, email) values ('Suite 72', '$2a$04$0HWVQQhE7/rpoBa9bxxh3OmQ57mUBzAX8BgwJNbjQyGmNobw/Jpty', 'banthon1g', 'zmelmoth1g@chronoengine.com');
insert into usuario (direccion, password, username, email) values ('PO Box 33081', '$2a$04$axsvbhsDi/sbLfg34fstX.9mufybaWc79dGCEBNiPFxA.pOBDBrxu', 'acassel1h', 'pslimon1h@pen.io');
insert into usuario (direccion, password, username, email) values ('Suite 71', '$2a$04$LzSJmMKNIu9HHTIla4.XB.8Llfc2o/J9bF/Pcl40U9YChK9b8df1a', 'dcrehan1i', 'apeskett1i@google.de');
insert into usuario (direccion, password, username, email) values ('5th Floor', '$2a$04$o8WF9ZpTMTbwdbb0fNml6ecP/980brxQlGUYViWogmPfhC7LZNZ2O', 'nblackstock1j', 'tdrewery1j@twitter.com');
insert into usuario (direccion, password, username, email) values ('Room 1631', '$2a$04$nEaRzbgTMqLIGs3rf4tM.OP1Si2SmYXRoXeG.rY4gWFacXzbJxDFS', 'tlillecrop1k', 'aturpie1k@storify.com');
insert into usuario (direccion, password, username, email) values ('Apt 1566', '$2a$04$L5GWurx6ehMxjZkdlN9P0uSUzkhK/bABU6RmikKgtzLevAoyat.Zq', 'njedrachowicz1l', 'ptwentyman1l@nsw.gov.au');
insert into usuario (direccion, password, username, email) values ('15th Floor', '$2a$04$SRq.tce29XUVyK260Hjux.Yfyui9.53qCSqS6KnY6CneAzmWaUTka', 'ccircuitt1m', 'rnairne1m@virginia.edu');
insert into usuario (direccion, password, username, email) values ('Suite 35', '$2a$04$TNW4gVH2uHfm9INbMwJVouqLg2MjxtZrxcfDr/5EBSnlfYw8jH8Nq', 'sbrewse1n', 'aparaman1n@accuweather.com');
insert into usuario (direccion, password, username, email) values ('Apt 1003', '$2a$04$mSYWeP1tANFfbMQnV.mStOmlBK5XfCeDCJN8VwavRjceWjijGycc2', 'ktorald1o', 'wdobbins1o@vistaprint.com');
insert into usuario (direccion, password, username, email) values ('PO Box 80060', '$2a$04$RG2CmKU8dWKLy12a0ch.xOGbqcKNtHLGdH6jqt7T34df9Tv0OKznS', 'psargint1p', 'mmuckleston1p@bigcartel.com');
insert into usuario (direccion, password, username, email) values ('Room 1180', '$2a$04$LXxacjbgLOdA4sJdPCZ3sOQKo5RT1lO4yQu5ucs5JbQrf5EAQXkmm', 'hvoelker1q', 'jstorre1q@people.com.cn');
insert into usuario (direccion, password, username, email) values ('17th Floor', '$2a$04$tV4NPbUdzYo1cBPutRQHkujGKr0fdsickuqyggGQvQib/XoBSxuNW', 'wbaseley1r', 'eupson1r@abc.net.au');
insert into usuario (direccion, password, username, email) values ('20th Floor', '$2a$04$N2peEi/4NrzEDKtzLTTnKObScY5jlABp.3z/CGhb7Ho.jdlhxMTyS', 'jberzon1s', 'rjustham1s@blogs.com');
insert into usuario (direccion, password, username, email) values ('PO Box 44086', '$2a$04$YFl0bqdJeKFtJ87W23Bc1.BiU0Om2vBNxcvuZpgCwU/h9Ffzm7qPy', 'kdefries1t', 'iiseton1t@blinklist.com');
insert into usuario (direccion, password, username, email) values ('11th Floor', '$2a$04$0nKsZas9ucdEiTHcRzRmK.5zwiXqkyLcfQHmGRGMigPHNnMQl1M2K', 'shayhurst1u', 'alindholm1u@pbs.org');
insert into usuario (direccion, password, username, email) values ('Apt 137', '$2a$04$eVJrcrxCSPAKThBaG5OcquJ30L7w43Xp1jCvLM7VUj4cszGl8bcNC', 'mgandrich1v', 'nlittrell1v@geocities.jp');
insert into usuario (direccion, password, username, email) values ('Suite 21', '$2a$04$xAoC319c.VSrA3i9z.ThXuK0Pq6NGDAyWlTsHliAKNFej0NYPZRrW', 'siacapucci1w', 'gbronot1w@jalbum.net');
insert into usuario (direccion, password, username, email) values ('1st Floor', '$2a$04$beF1ZpezSYlBwj4Q2PyG6.MlScCJdZNvnAFeEdamgxjXbJ/UE5nTm', 'hcastanone1x', 'cbeswick1x@ifeng.com');
insert into usuario (direccion, password, username, email) values ('Room 1358', '$2a$04$7O5B0I8HpJw7pSXL2yYTaub5oMlBBfDi7vFTHwpwAMgqNg2i91jX.', 'mduffell1y', 'nesplin1y@forbes.com');
insert into usuario (direccion, password, username, email) values ('Suite 40', '$2a$04$ptxpCycC.QoCFj9O7zCR2OiYSWUutr0qv4n5fpyQ3JSPj.65TfXw.', 'vlescop1z', 'tduffer1z@google.co.jp');
insert into usuario (direccion, password, username, email) values ('4th Floor', '$2a$04$4GDAZ9Ga7GeFRx5CjFzoiubnSoSJ86.jFF3i0Us0bXX2iT7B84F9y', 'chalso20', 'gbartoletti20@macromedia.com');
insert into usuario (direccion, password, username, email) values ('PO Box 89168', '$2a$04$43b58k1N4EXJLbyKOUyv5.7hX0X6H3Dx6KVnrGe/sZ2N8Lth/u8cC', 'igyer21', 'vallott21@ovh.net');
insert into usuario (direccion, password, username, email) values ('PO Box 34324', '$2a$04$2czA.vwoBufE/rYieL9E5ekskHL6UWkcMHxj6IefT8ylf1PoxzFIC', 'ternke22', 'hbarradell22@miitbeian.gov.cn');
insert into usuario (direccion, password, username, email) values ('Apt 27', '$2a$04$OsMQHoGKDpEupqdsG04LT.nWvoMmfwwQ10C/jXCeEDiHpZnvjwE02', 'evictor23', 'wtilford23@a8.net');
insert into usuario (direccion, password, username, email) values ('PO Box 18784', '$2a$04$b.tLFybEi3xWeyfLRVxzKuD5RMlt5JeZljHVPtk5OGY2jbGrFfrHu', 'lbrideaux24', 'kskeat24@github.io');
insert into usuario (direccion, password, username, email) values ('Suite 83', '$2a$04$SjTSeFs.L0EjguO/fk8e6OUTiye2n6WbMa5aODheB.Sv2/AxZBpEe', 'aholworth25', 'ibettleson25@woothemes.com');
insert into usuario (direccion, password, username, email) values ('PO Box 90537', '$2a$04$S.9D2gWzsezgLqYY6eBIb./xmh1ordF0QWYM2OatOFXu1PdLIyCbq', 'mbawles26', 'sborwick26@ehow.com');
insert into usuario (direccion, password, username, email) values ('Apt 1304', '$2a$04$4218JBv.L1U7iHdScBhZmexdCEUDwJZWJCZsnrzMpA2NMkcqJgS1a', 'ppottiphar27', 'abarwell27@cyberchimps.com');
insert into usuario (direccion, password, username, email) values ('Suite 15', '$2a$04$gD/quPa0tYPV3MikI6fNZuSrOklt.UYFjPDn8CSHSrHxPsY0jtuHW', 'rmalter28', 'ahanbury28@networkadvertising.org');
insert into usuario (direccion, password, username, email) values ('20th Floor', '$2a$04$yK/mDsmSo/R4aGVQP5SjBOlaDcklDwDcE/cA/S5Ud6UU13SJBqz.m', 'pofaherty29', 'mceland29@intel.com');
insert into usuario (direccion, password, username, email) values ('Room 561', '$2a$04$RsDUR0TIda1M3LlsA2MaJOKCEu9t47/DFqo1mOqzd54BNy0ubqD1C', 'mwoller2a', 'kjobern2a@epa.gov');
insert into usuario (direccion, password, username, email) values ('Room 1410', '$2a$04$ZnlVDQnIWUAIcCEwBqKfgOY83OQTdUgP/tHKsBQa3psfm0F2NZAya', 'bbawle2b', 'hyexley2b@chronoengine.com');
insert into usuario (direccion, password, username, email) values ('PO Box 15119', '$2a$04$nkckbJiSoAOQz0Rievt8BOs/6HdOGvG79hcpDqgpkP4YuC05Ufs4i', 'ttonkinson2c', 'dgilmore2c@odnoklassniki.ru');
insert into usuario (direccion, password, username, email) values ('13th Floor', '$2a$04$W45fwBy1jYSEAxdrchbBKOTGkylWunVD/bIm13aMZrlDDq5Hj5Zf2', 'rspawell2d', 'dolyff2d@wunderground.com');
insert into usuario (direccion, password, username, email) values ('7th Floor', '$2a$04$zr4/Ih4kbazKpbyeMRHhtu22HEuKr/AEK.IeckgbMcXvry3l21xHW', 'tlehrian2e', 'mcolombier2e@ibm.com');
insert into usuario (direccion, password, username, email) values ('Room 1909', '$2a$04$UTS8Qh8UGN6oC5j6fSpmyezggzuVraVY9jOFNQNJPyjkxB.FP1uwW', 'sradbond2f', 'ggerraty2f@scientificamerican.com');
insert into usuario (direccion, password, username, email) values ('Apt 1043', '$2a$04$oM2K7WCoDeVnJ.e2L3QE2eAiWlYJHtybcTt5YMbnYthAsEkFcDZOG', 'egraybeal2g', 'rchevolleau2g@tumblr.com');
insert into usuario (direccion, password, username, email) values ('PO Box 89298', '$2a$04$XNdo9HyVCCk7u805G8hdFO4UR.c6Vu5fOWeilth/RE.TFuBdnAWIq', 'gmaudlin2h', 'ghelleker2h@woothemes.com');
insert into usuario (direccion, password, username, email) values ('Room 545', '$2a$04$Vm/zrr5yQIg.tdvfUAxwCeKudjwlsUzl1XLd7zOQr7Z7bGFHe1PWq', 'ekienle2i', 'crait2i@nifty.com');
insert into usuario (direccion, password, username, email) values ('11th Floor', '$2a$04$nC48MIIfSb.BBHs/K3q/oOh3jWREzn3/mh5M.KbJ3jV8CzeN4SYdi', 'mkorneichik2j', 'sbraybrooke2j@wikimedia.org');
insert into usuario (direccion, password, username, email) values ('1st Floor', '$2a$04$jqqK3kkAZ1K10EZApwuRtu3LNEcgbttzSXvEa/OzTvHTq0tydE.tC', 'jthurling2k', 'kibberson2k@shop-pro.jp');
insert into usuario (direccion, password, username, email) values ('8th Floor', '$2a$04$VY/cQJAEqVWQ0KW3FSnoj.dPqRCW80rwnJTjR1bYpcX7ieFva1O0S', 'bbowick2l', 'wrossetti2l@discovery.com');
insert into usuario (direccion, password, username, email) values ('17th Floor', '$2a$04$zBLI/hR1Pgt.oFlFHLWnzuwbmtpFWN/a7clzwmbJPDlUeC4k4oTGe', 'ecrowhurst2m', 'mogdahl2m@rambler.ru');
insert into usuario (direccion, password, username, email) values ('Room 88', '$2a$04$.A5.J7Gq/7VE32VnDKaRiOMVUU8eEZt4qE3m9beXhqy/HzGPAwhlu', 'bregorz2n', 'mduckett2n@ask.com');
insert into usuario (direccion, password, username, email) values ('8th Floor', '$2a$04$3kQ4ludVVedauSo/h6GiweWas3sVrh/sm5NQThM2akrbYTipil4nS', 'mwestman2o', 'tgregorin2o@webeden.co.uk');
insert into usuario (direccion, password, username, email) values ('PO Box 25991', '$2a$04$BiSoxJPtbB9fzwb5Jfrg6uRy.yj8YY03MgYWCht6Z9mSQ8NaESkry', 'mravenscroftt2p', 'pgosney2p@spiegel.de');
insert into usuario (direccion, password, username, email) values ('Room 618', '$2a$04$SIZcz5mTocSon6B6C4imPO93w8RnE9OYQYZ18h6UbWcaNzyA55H1.', 'adury2q', 'eclose2q@behance.net');
insert into usuario (direccion, password, username, email) values ('Suite 61', '$2a$04$OnNrBbCvIWKknAqVuXSifuh8j2SzZdcceI3Ux3DChchanOEnoAmjK', 'sfones2r', 'bpywell2r@paypal.com');